spring:
  application:
    name: GraduationProjectTestApp
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5442/graduation_project}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

svg-maker:
  base-url: ${SVG_MAKER_URL:http://localhost:5123/api}
